name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build1:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build all test images
      #--force-rm: Always remove intermediate containers
      #--progress=plain
      run: |
        docker build nanoserver --force-rm --rm --no-cache --tag nanoserver:$(date +%s)

  build2:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build all test images
      run: |
        docker build servercore --force-rm --rm --no-cache --tag servercore:$(date +%s)
