# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ##########################################################################################
  build:
    name: "Build - Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    # ref: https://github.com/mikepenz/action-junit-report/issues/23
    # ref: https://github.com/orgoro/coverage/issues/310
    # ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    # required for junit report

    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
          - windows-latest
        python-version:
          #- "3.10"
          - "3.13"
      # Let the other builds complete if one is failed.
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: "Set up Python ${{ matrix.python-version }}"
      uses: "actions/setup-python@v5"
      with:
        python-version: ${{ matrix.python-version }}

    - name: Info
      run: |
        python --version
        python -m pip --version
        python -m pip list

    - name: Install first
      run: |
        python -m pip install PyPDF2
        python -m pip list
        python -c "import PyPDF2 as p; print(p.__file__)"

    - name: Uninstall
      run: |
        python -m pip uninstall -y PyPDF2
        python -m pip list

    - name: Install 2nd time
      run: |
        python -m pip install PyPDF2
        python -m pip list
        python -c "import PyPDF2 as p; print(p.__file__)"
